---
- name: Get container facts
  kolla_container_facts:
    name:
      - kibana
  register: container_facts

- name: Checking free port for Kibana Server
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ kibana_server_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['kibana'] is not defined
    - inventory_hostname in groups['kibana']
