- name: create pre-configured repo files
  file:
    path: /etc/yum.repos.d
    state: directory

- name: config base repo
  get_url:
    url: http://{{ deploy_server_hostname }}/repo_files/base.repo
    dest: /etc/yum.repos.d/base.repo

- name: config updates repo
  get_url:
    url: http://{{ deploy_server_hostname }}/repo_files/updates.repo
    dest: /etc/yum.repos.d/updates.repo

- name: config epel repo
  get_url:
    url: http://{{ deploy_server_hostname }}/repo_files/epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name: config extras repo
  get_url:
    url: http://{{ deploy_server_hostname }}/repo_files/extras.repo
    dest: /etc/yum.repos.d/extras.repo
