---
- name: install {{ docker_repo_name }} repo
  yum_repository:
    name: "{{ docker_repo_name }}"
    description: "{{ docker_repo_name }}"
    baseurl: "{{ osc_rpm_repository_url }}/{{ docker_repo_name }}"
    gpgcheck: no

- name: yum clean all
  shell: yum clean all
  ignore_errors: yes

- name: sync docker repo
  shell: reposync --repoid="{{ docker_repo_name }}" --download_path={{ local_rpm_repository_path }}/

- name: create repo of docker
  shell: createrepo {{ local_rpm_repository_path }}/{{ docker_repo_name }}
